package br.com.financeiroweb.pojo;
// default package
// Generated 28/09/2014 14:04:16 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CondicaoDePagamento generated by hbm2java
 */
@Entity
@Table(name = "condicao_de_pagamento", catalog = "financeiroweb")
public class CondicaoDePagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	private int parcela;
	private int intervalo;
	private Set<HistoricoMovimento> historicoMovimentos = new HashSet<HistoricoMovimento>(
			0);
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);

	public CondicaoDePagamento() {
	}

	public CondicaoDePagamento(String nome, int parcela, int intervalo) {
		this.nome = nome;
		this.parcela = parcela;
		this.intervalo = intervalo;
	}

	public CondicaoDePagamento(String nome, int parcela, int intervalo,
			Set<HistoricoMovimento> historicoMovimentos,
			Set<Movimento> movimentos) {
		this.nome = nome;
		this.parcela = parcela;
		this.intervalo = intervalo;
		this.historicoMovimentos = historicoMovimentos;
		this.movimentos = movimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "parcela", nullable = false)
	public int getParcela() {
		return this.parcela;
	}

	public void setParcela(int parcela) {
		this.parcela = parcela;
	}

	@Column(name = "intervalo", nullable = false)
	public int getIntervalo() {
		return this.intervalo;
	}

	public void setIntervalo(int intervalo) {
		this.intervalo = intervalo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoDePagamento")
	public Set<HistoricoMovimento> getHistoricoMovimentos() {
		return this.historicoMovimentos;
	}

	public void setHistoricoMovimentos(
			Set<HistoricoMovimento> historicoMovimentos) {
		this.historicoMovimentos = historicoMovimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoDePagamento")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
