package br.com.financeiroweb.pojo;
// default package
// Generated 28/09/2014 14:04:16 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContaContabil generated by hbm2java
 */
@Entity
@Table(name = "conta_contabil", catalog = "financeiroweb")
public class ContaContabil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	private String codigo;
	private boolean tipo;
	private Set<PlanoDeContas> planoDeContases = new HashSet<PlanoDeContas>(0);
	private Set<HistoricoMovimento> historicoMovimentos = new HashSet<HistoricoMovimento>(
			0);
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);

	public ContaContabil() {
	}

	public ContaContabil(String nome, String codigo, boolean tipo) {
		this.nome = nome;
		this.codigo = codigo;
		this.tipo = tipo;
	}

	public ContaContabil(String nome, String codigo, boolean tipo,
			Set<PlanoDeContas> planoDeContases,
			Set<HistoricoMovimento> historicoMovimentos,
			Set<Movimento> movimentos) {
		this.nome = nome;
		this.codigo = codigo;
		this.tipo = tipo;
		this.planoDeContases = planoDeContases;
		this.historicoMovimentos = historicoMovimentos;
		this.movimentos = movimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "tipo", nullable = false)
	public boolean isTipo() {
		return this.tipo;
	}

	public void setTipo(boolean tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaContabil")
	public Set<PlanoDeContas> getPlanoDeContases() {
		return this.planoDeContases;
	}

	public void setPlanoDeContases(Set<PlanoDeContas> planoDeContases) {
		this.planoDeContases = planoDeContases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaContabil")
	public Set<HistoricoMovimento> getHistoricoMovimentos() {
		return this.historicoMovimentos;
	}

	public void setHistoricoMovimentos(
			Set<HistoricoMovimento> historicoMovimentos) {
		this.historicoMovimentos = historicoMovimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaContabil")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

}
