package br.com.financeiroweb.pojo;
// default package
// Generated 28/09/2014 14:04:16 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name = "contato", catalog = "financeiroweb")
public class Contato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String telefone;
	private String celular;
	private String email;
	private Set<ClienteFornecedor> clienteFornecedors = new HashSet<ClienteFornecedor>(
			0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public Contato() {
	}

	public Contato(String telefone, String celular, String email) {
		this.telefone = telefone;
		this.celular = celular;
		this.email = email;
	}

	public Contato(String telefone, String celular, String email,
			Set<ClienteFornecedor> clienteFornecedors, Set<Empresa> empresas) {
		this.telefone = telefone;
		this.celular = celular;
		this.email = email;
		this.clienteFornecedors = clienteFornecedors;
		this.empresas = empresas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "telefone", nullable = false, length = 45)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "celular", nullable = false, length = 45)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contato")
	public Set<ClienteFornecedor> getClienteFornecedors() {
		return this.clienteFornecedors;
	}

	public void setClienteFornecedors(Set<ClienteFornecedor> clienteFornecedors) {
		this.clienteFornecedors = clienteFornecedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contato")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
